### ISSUE TITLE
Does not compile on CUDA 12.0

### ISSUE THREAD

**Issue by jtang613** [qwopqwop200/GPTQ-for-LLaMa#7]
On running the setup_cuda.py install, I was initially getting:
`RuntimeError: 
The detected CUDA version (12.0) mismatches the version that was used to compile
PyTorch (11.8). Please make sure to use the same CUDA versions.
`

Tried being clever and manually compiling which returned the following errors:
`
/usr/local/lib64/python3.11/site-packages/torch/include/ATen/core/qualified_name.h(73): here

/usr/local/lib64/python3.11/site-packages/torch/include/pybind11/detail/../cast.h: In function ‘typename pybind11::detail::type_caster<typename pybind11::detail::intrinsic_type<T>::type>::cast_op_type<T> pybind11::detail::cast_op(make_caster<T>&)’:
/usr/local/lib64/python3.11/site-packages/torch/include/pybind11/detail/../cast.h:42:120: error: expected template-name before ‘<’ token
   42 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
      |                                                                                                                        ^
/usr/local/lib64/python3.11/site-packages/torch/include/pybind11/detail/../cast.h:42:120: error: expected identifier before ‘<’ token
/usr/local/lib64/python3.11/site-packages/torch/include/pybind11/detail/../cast.h:42:123: error: expected primary-expression before ‘>’ token
   42 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
      |                                                                                                                           ^
/usr/local/lib64/python3.11/site-packages/torch/include/pybind11/detail/../cast.h:42:126: error: expected primary-expression before ‘)’ token
   42 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
      |                                                                                           
`

**Comment by jtang613** [comment]
Edit: I realise this is probably a pytorch limitation. Closing...

**Comment by C0rn3j** [comment]
https://github.com/pytorch/pytorch/issues/91122

**Comment by jtang613** [comment]
fwiw: I'm running Fedora 37.  I ended up needing to downgrade from CUDA 12 to CUDA 11.8 (from the Fedora 35 repos), then installed LinuxBrew so that I could install gcc-11 because F37's gcc-12 is also too new. After that, it worked.

**Comment by theAdamColton** [comment]
For anyone else who find this, I was able to build this on linux after setting my CUDA_HOME, CC and CXX variables: `export CUDA_HOME=$CONDA_PREFIX/` `export CXX=/usr/bin/g++-11` `export CC=/usr/bin/gcc-11`
